version: '3.10'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
  db:
    image: "postgres:14"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: