# Generated by Django 5.0.3 on 2024-03-24 20:28

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
import django.db.models.deletion
import job.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=256, null=True)),
                ('jobType', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Internship', 'Internship'), ('Voluntarily', 'Voluntarily'), ('Part Time', 'Parttime')], default='Permanent', max_length=32)),
                ('education', models.CharField(choices=[('High School Degree', 'Highschool'), ('Associate Degree', 'Associatedegree'), ('Bachelor Degree', 'Bachelors'), ('Master Degree', 'Masters'), ('Phd', 'Phd')], default='Bachelor Degree', max_length=32)),
                ('industry', models.CharField(choices=[('Business', 'Business'), ('Information Technology', 'It'), ('Finance', 'Finance'), ('Telecommuication', 'Telecommunication'), ('Education/Training', 'Education'), ('Healthcare', 'Healthcare'), ('Human Resource', 'Hr'), ('Aviation', 'Aviation'), ('Sales', 'Sales'), ('Accounting', 'Accounting'), ('Management', 'Management'), ('Others', 'Others')], default='Information Technology', max_length=32)),
                ('experience', models.CharField(choices=[('New Graduate', 'Newgraduate'), ('1 Year', 'Oneyear'), ('2 Year', 'Twoyear'), ('3 Year and Above', 'Threeyearplus')], default='New Graduate', max_length=32)),
                ('salary', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999999)])),
                ('positions', models.IntegerField(default=1)),
                ('company', models.CharField(max_length=100, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
                ('deadline', models.DateTimeField(default=job.models.return_date_time)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
